# Generated by Django 3.2.4 on 2021-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_description', models.TextField(blank=True, null=True)),
                ('feature_type', models.CharField(choices=[('Principle', 'Principle'), ('Value', 'Value')], default='Feature', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
